### PR TITLE
Update upgrade

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by tituspijean — COMMENTED** [review]
You should remove all the `.DS_Store` files. ;)

**Comment by ericgaspar** [comment]
damnit!

**Comment by ericgaspar** [comment]
!tastemetitus

**Review by alexAubin — APPROVED** [review]
LGTM, to be validated by the CI

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Pull request merged**
